### PR TITLE
added support for quart framework

### PR DESCRIPTION
**Pull request by Darkless012**
Quart is async Flask-like API compatible framework.

Logging setup still needs some minor polishing, but it is "ready" to be merged. 

Request logging works, other logging works as well.

### CODE REVIEW

**Comment by thangbn** [comment]
@Darkless012 thanks for PR. It looks great. 👍 
Just one more thing, could u pls add an example script into example folder and update readme accordingly.
After that i will do the build and release it to PyPi

**Comment by Darkless012** [comment]
Thanks for the remarks, I didn't rebased on current master though, will you be able to resolve README.md, or should I fix that?

**Comment by thangbn** [comment]
i will take care of it and do a release

**Comment by thangbn** [comment]
released : https://pypi.org/project/json-logging/0.0.9/
Thanks again for great contribution!

**Pull request merged**
