### PR TITLE
Fix value vs object identity error (closes #39)

### LINKED ISSUE #39: Fix Python 3.8 SyntaxWarnings
Annoying and easy to fix:

```
json_logging-1.0.5-py2.py3-none-any.whl/json_logging/util.py:187: 
SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if key is not 'request' and key is not 'req':
```

### PR DESCRIPTION
**Pull request by jhermann**

### CODE REVIEW

**Comment by jhermann** [comment]
And BTW…

    json_logging/__init__.py:193:8: E1003: Bad first argument 'self.__class__' given to super() (bad-super-call)

And no, I won't make another 1liner PR, it is easy to fix yourself.

**Comment by thangbn** [comment]
> And BTW…
> 
> ```
> json_logging/__init__.py:193:8: E1003: Bad first argument 'self.__class__' given to super() (bad-super-call)
> ```
> 
> And no, I won't make another 1liner PR, it is easy to fix yourself.

when do u see it happen?

**Comment by thangbn** [comment]
released https://pypi.org/project/json-logging/1.0.6/

**Comment by jhermann** [comment]
> when do u see it happen?

The above is pylint output. pip install + call it. You call is still Python2.

**Pull request merged**
